const mongoose = require("mongoose");

const attendanceRecordSchema = new mongoose.Schema(
  {
    employee: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "EmployeeRegistration",
      required: true,
    },
    empId: {
      type: String,
      required: true,
    },
    employeeName: {
      type: String,
      required: true,
    },
    date: {
      type: Date,
      required: true,
    },
    punchIn: {
      time: { type: Date },
      location: { type: String },
      coordinates: {
        latitude: { type: Number },
        longitude: { type: Number },
      },
      faceVerified: { type: Boolean, default: false },
      confidence: { type: Number },
      ipAddress: { type: String },
      device: { type: String },
    },
    punchOut: {
      time: { type: Date },
      location: { type: String },
      coordinates: {
        latitude: { type: Number },
        longitude: { type: Number },
      },
      faceVerified: { type: Boolean, default: false },
      confidence: { type: Number },
      ipAddress: { type: String },
      device: { type: String },
    },
    status: {
      type: String,
      enum: ["Present", "Late", "Absent", "Leave", "Half Day"],
      default: "Present",
    },
    workingHours: {
      type: Number,
      default: 0,
    },
    overtimeHours: {
      type: Number,
      default: 0,
    },
    breakTime: {
      type: Number,
      default: 0,
    },
    isAbsent: {
      type: Boolean,
      default: false,
    },
    leaveType: {
      type: String,
      enum: ["Sick Leave", "Casual Leave", "Annual Leave", "Emergency Leave"],
    },
    leaveReason: {
      type: String,
    },
    notes: {
      type: String,
    },
    approved: {
      type: Boolean,
      default: true,
    },
    approvedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
    },
    autoGenerated: {
      type: Boolean,
      default: false,
    },
  },
  {
    timestamps: true,
  }
);

// Calculate working hours before saving
attendanceRecordSchema.pre("save", function (next) {
  if (this.punchIn?.time && this.punchOut?.time && this.status !== "Absent") {
    const punchInTime = new Date(this.punchIn.time);
    const punchOutTime = new Date(this.punchOut.time);

    const diffMs = punchOutTime - punchInTime;
    const diffHours = diffMs / (1000 * 60 * 60);

    this.workingHours = Math.max(0, diffHours - (this.breakTime || 0));

    // Calculate overtime (assuming 8 hours is standard)
    if (this.workingHours > 8) {
      this.overtimeHours = this.workingHours - 8;
    }
  }
  next();
});

// Compound index to ensure one attendance record per employee per day
attendanceRecordSchema.index({ employee: 1, date: 1 }, { unique: true });
attendanceRecordSchema.index({ empId: 1, date: 1 });
attendanceRecordSchema.index({ date: 1 });
attendanceRecordSchema.index({ status: 1 });

module.exports = mongoose.models.AttendanceRecord || mongoose.model("AttendanceRecord", attendanceRecordSchema);
