const mongoose = require('mongoose');
const AttendanceMaster = require('../model/AttendanceMaster');
const AttendanceRecord = require('../model/AttendanceRecord');


exports.processDailyAttendance = async (req, res) => {
  try {
    // Handle undefined req.body and provide default date
    const requestDate = req.body?.date || req.query?.date;
    const targetDate = requestDate ? new Date(requestDate) : new Date();
    
    // Set to start of day to avoid time zone issues
    targetDate.setHours(0, 0, 0, 0);
    
    console.log(`Processing attendance for date: ${targetDate.toDateString()}`);
    
    // Get all active masters
    const masters = await AttendanceMaster.find({ isActive: true }).lean();
    const updates = [];
    
    for (const master of masters) {
      // Check if it's a working day
      const dayNames = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];
      const dayName = dayNames[targetDate.getDay()];
      const isWorkingDay = !master.weeklyOffDays.includes(dayName);
      
      if (!isWorkingDay) {
        console.log(`Skipping ${master.empId} - ${dayName} is not a working day`);
        continue;
      }
      
      // Check if attendance record already exists
      const startOfDay = new Date(targetDate);
      const endOfDay = new Date(targetDate);
      endOfDay.setHours(23, 59, 59, 999);
      
      const existingRecord = await AttendanceRecord.findOne({
        employeeId: master.employeeId,
        date: {
          $gte: startOfDay,
          $lte: endOfDay
        }
      });
      
      if (!existingRecord) {
        console.log(`Creating absent record for ${master.empId}`);
        
        // Create absent record
        const status = determineAttendanceStatus({
          hasCheckIn: false,
          hasLeaveRequest: false,
          isWeekend: false,
          isHoliday: false
        }, targetDate);
        
        if (status) {
          updates.push({
            employeeId: master.employeeId,
            empId: master.empId,
            employeeName: master.employeeName,
            date: targetDate,
            ...status,
            autoGenerated: true,
            approved: true
          });
        }
      } else {
        console.log(`Record already exists for ${master.empId}`);
      }
    }
    
    // Bulk insert missing attendance records
    let insertedRecords = [];
    if (updates.length > 0) {
      insertedRecords = await AttendanceRecord.insertMany(updates);
      console.log(`Created ${insertedRecords.length} attendance records`);
    }
    
    res.status(200).json({
      success: true,
      message: `Processed daily attendance for ${targetDate.toDateString()}`,
      date: targetDate.toDateString(),
      totalMasters: masters.length,
      recordsCreated: insertedRecords.length,
      data: updates
    });
    
  } catch (error) {
    console.error('Process daily attendance error:', error);
    res.status(500).json({
      success: false,
      message: 'Error processing daily attendance',
      error: error.message
    });
  }
};