const mongoose = require('mongoose');
const AttendanceMaster = require('../RestautantModel/RestaurantAttendanceMaster');
const Employee = require('../RestautantModel/RestaurantEmployeeSchema');
const AttendanceRecord = require('../RestautantModel/RestaurantAttendanceRecord'); 
/**
 * Get all attendance masters (keeping your original simple version)
 */
const ATTENDANCE_STATUS = {
  PRESENT: 'present',
  ABSENT: 'absent',
  LEAVE: 'leave', 
  HALF_DAY: 'half-day',
  NO_SHOW: 'no-show',
  LATE: 'late'
};

const LEAVE_TYPES = {
  PAID: 'paid',
  UNPAID: 'unpaid',
  SEEK: 'seek',
  CASUAL: 'casual',
  EMERGENCY: 'emergency'
};
// Add this function at the top of attendanceMasterController.js
const determineAttendanceStatus = (attendanceData, date) => {
  const dayNames = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];
  const dayName = dayNames[date.getDay()];
  
  // Check if it's a weekend
  if (['Saturday', 'Sunday'].includes(dayName)) {
    return { status: 'weekend' };
  }
  
  // Check if employee didn't show up and it's a working day
  if (!attendanceData.hasCheckIn && !attendanceData.hasLeaveRequest) {
    return { status: 'absent' };
  }
  
  return null;
};

// Fix the processDailyAttendance function
exports.processDailyAttendance = async (req, res) => {
  try {
    const requestDate = req.body?.date || req.query?.date;
    const targetDate = requestDate ? new Date(requestDate) : new Date();
    targetDate.setHours(0, 0, 0, 0);
    
    console.log(`Processing attendance for date: ${targetDate.toDateString()}`);
    
    // Get all active masters
    const masters = await AttendanceMaster.find({ isActive: true }).lean();
    const updates = [];
    
    for (const master of masters) {
      // Check if it's a working day
      const dayNames = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];
      const dayName = dayNames[targetDate.getDay()];
      const isWorkingDay = !master.weeklyOffDays.includes(dayName);
      
      if (!isWorkingDay) {
        console.log(`Skipping ${master.empId} - ${dayName} is not a working day`);
        continue;
      }
      
      // Check if attendance record already exists
      const startOfDay = new Date(targetDate);
      const endOfDay = new Date(targetDate);
      endOfDay.setHours(23, 59, 59, 999);
      
      const existingRecord = await AttendanceRecord.findOne({
        employeeId: master.employeeId,
        date: {
          $gte: startOfDay,
          $lte: endOfDay
        }
      });
      
      if (!existingRecord) {
        console.log(`Creating absent record for ${master.empId}`);
        
        // Create absent record
        updates.push({
          employeeId: master.employeeId,
          empId: master.empId,
          employeeName: master.employeeName,
          date: targetDate,
          status: 'absent',
          autoGenerated: true,
          approved: true,
          notes: 'Auto-generated absent record'
        });
      } else {
        console.log(`Record already exists for ${master.empId}`);
      }
    }
    
    // Bulk insert missing attendance records
    let insertedRecords = [];
    if (updates.length > 0) {
      insertedRecords = await AttendanceRecord.insertMany(updates);
      console.log(`Created ${insertedRecords.length} attendance records`);
    }
    
    res.status(200).json({
      success: true,
      message: `Processed daily attendance for ${targetDate.toDateString()}`,
      date: targetDate.toDateString(),
      totalMasters: masters.length,
      recordsCreated: insertedRecords.length,
      data: updates
    });
    
  } catch (error) {
    console.error('Process daily attendance error:', error);
    res.status(500).json({
      success: false,
      message: 'Error processing daily attendance',
      error: error.message
    });
  }
};
exports.getAllAttendanceMasters = async (req, res) => {
  try {
    const masters = await AttendanceMaster.find({ isActive: true })
      .sort({ department: 1, employeeName: 1 })
      .lean();

    res.status(200).json({
      success: true,
      count: masters.length,
      data: masters,
      totalCount: masters.length
    });
  } catch (error) {
    console.error('Error fetching attendance masters:', error);
    res.status(500).json({
      success: false,
      message: 'Error fetching attendance masters',
      error: error.message
    });
  }
};

/**
 * Get attendance master by ID
 */
exports.getAttendanceMasterById = async (req, res) => {
  try {
    const master = await AttendanceMaster.findById(req.params.id).lean();
    
    if (!master) {
      return res.status(404).json({
        success: false,
        message: 'Attendance master not found'
      });
    }

    res.status(200).json({
      success: true,
      data: master
    });
  } catch (error) {
    console.error('Error fetching attendance master:', error);
    res.status(500).json({
      success: false,
      message: 'Error fetching attendance master',
      error: error.message
    });
  }
};

/**
 * Create attendance master
 */
exports.createAttendanceMaster = async (req, res) => {
  try {
    const { empId, employeeName, department, shift, workingDaysPerMonth, weeklyOffDays, gracePeriod, overtimeRate } = req.body;

    // Check if already exists
    const existing = await AttendanceMaster.findOne({ empId, isActive: true });
    if (existing) {
      return res.status(400).json({
        success: false,
        message: 'Attendance master already exists for this employee'
      });
    }

    // Get employee details for validation
    // Try to find by employeeId first (if empId matches the format), then by _id
    let employee = await Employee.findOne({ employeeId: empId }).lean();
    if (!employee) {
      // Try finding by _id if empId is an ObjectId string
      if (mongoose.Types.ObjectId.isValid(empId)) {
        employee = await Employee.findById(empId).lean();
      }
    }
    if (!employee) {
      return res.status(404).json({
        success: false,
        message: 'Employee not found'
      });
    }

    const attendanceMasterData = {
      empId: employee.employeeId || empId, // Use employee.employeeId if available, otherwise use provided empId
      employeeId: employee._id,
      employeeName: employeeName || employee.name.trim(),
      department: department || employee.department,
      shift: shift || {
        type: 'Morning',
        startTime: '10:00',
        endTime: '18:00',
        breakDuration: 60
      },
      workingDaysPerMonth: workingDaysPerMonth || 26,
      weeklyOffDays: weeklyOffDays || ['Saturday', 'Sunday'],
      gracePeriod: gracePeriod || 15,
      overtimeRate: overtimeRate || 1.5,
      paidLeaveAllowance: 2,
      isActive: true
    };

    let attendanceMaster;

    // If updating existing (deactivated), update it
    const inactiveMaster = await AttendanceMaster.findOne({ empId, isActive: false });
    if (inactiveMaster) {
      Object.assign(inactiveMaster, attendanceMasterData);
      inactiveMaster.isActive = true;
      attendanceMaster = await inactiveMaster.save();
    } else {
      // Create new
      attendanceMaster = new AttendanceMaster(attendanceMasterData);
      await attendanceMaster.save();
    }

    res.status(201).json({
      success: true,
      data: attendanceMaster
    });
  } catch (error) {
    console.error('Create master error:', error);
    res.status(500).json({
      success: false,
      message: 'Error creating attendance master',
      error: error.message
    });
  }
};

/**
 * Update attendance master
 */
exports.updateAttendanceMaster = async (req, res) => {
  try {
    const master = await AttendanceMaster.findByIdAndUpdate(
      req.params.id,
      req.body,
      { new: true, runValidators: true }
    );

    if (!master) {
      return res.status(404).json({
        success: false,
        message: 'Attendance master not found'
      });
    }

    res.status(200).json({
      success: true,
      data: master
    });
  } catch (error) {
    console.error('Update master error:', error);
    res.status(500).json({
      success: false,
      message: 'Error updating attendance master',
      error: error.message
    });
  }
};

/**
 * Delete attendance master (soft delete)
 */
exports.deleteAttendanceMaster = async (req, res) => {
  try {
    const master = await AttendanceMaster.findById(req.params.id);
    if (!master) {
      return res.status(404).json({
        success: false,
        message: 'Attendance master not found'
      });
    }

    master.isActive = false;
    await master.save();

    res.status(200).json({
      success: true,
      message: 'Attendance master deactivated successfully'
    });
  } catch (error) {
    console.error('Delete master error:', error);
    res.status(500).json({
      success: false,
      message: 'Error deactivating attendance master',
      error: error.message
    });
  }
};

/**
 * Bulk create attendance masters
 */
exports.bulkCreateAttendanceMasters = async (req, res) => {
  try {
    const { empIds } = req.body;
    
    if (!empIds || !Array.isArray(empIds) || empIds.length === 0) {
      return res.status(400).json({
        success: false,
        message: 'empIds array is required and cannot be empty'
      });
    }

    const createdMasters = [];
    const errors = [];
    let successCount = 0;

    console.log(`Processing bulk creation for ${empIds.length} employee IDs`);

    for (const empId of empIds) {
      try {
        // Check if already exists and active
        const existingActive = await AttendanceMaster.findOne({ empId, isActive: true });
        if (existingActive) {
          console.log(`Skipping ${empId} - already active`);
          continue;
        }

        // Get employee details
        // Try to find by employeeId first, then by _id
        let employee = await Employee.findOne({ employeeId: empId }).lean();
        if (!employee && mongoose.Types.ObjectId.isValid(empId)) {
          employee = await Employee.findById(empId).lean();
        }
        if (!employee) {
          errors.push({
            empId,
            error: 'Employee not found'
          });
          console.log(`Employee not found: ${empId}`);
          continue;
        }

        const attendanceMasterData = {
          empId: employee.employeeId || empId, // Use employee.employeeId if available
          employeeId: employee._id,
          employeeName: employee.name.trim(),
          department: employee.department,
          shift: {
            type: 'Morning',
            startTime: '10:00',
            endTime: '18:00',
            breakDuration: 60
          },
          workingDaysPerMonth: 26,
          weeklyOffDays: ['Saturday', 'Sunday'],
          gracePeriod: 15,
          overtimeRate: 1.5,
          paidLeaveAllowance: 2,
          isActive: true
        };

        // Check for inactive master
        const inactiveMaster = await AttendanceMaster.findOne({ empId, isActive: false });
        if (inactiveMaster) {
          // Reactivate existing inactive master
          Object.assign(inactiveMaster, attendanceMasterData);
          inactiveMaster.isActive = true;
          await inactiveMaster.save();
          createdMasters.push(inactiveMaster);
        } else {
          // Create new master
          const master = new AttendanceMaster(attendanceMasterData);
          await master.save();
          createdMasters.push(master);
        }

        successCount++;
        console.log(`Successfully processed ${empId}`);
      } catch (error) {
        console.error(`Error processing ${empId}:`, error.message);
        errors.push({
          empId,
          error: error.message
        });
      }
    }

    console.log(`Bulk creation completed: ${successCount} successful, ${errors.length} errors`);

    res.status(201).json({
      success: true,
      count: createdMasters.length,
      successful: successCount,
      errors: errors.length,
      data: createdMasters,
      errorDetails: errors
    });
  } catch (error) {
    console.error('Bulk create error:', error);
    res.status(500).json({
      success: false,
      message: 'Error creating bulk attendance masters',
      error: error.message
    });
  }
};

/**
 * Get available employees count (SIMPLE VERSION - uses existing employee API)
 */
exports.getAvailableEmployeesCount = async (req, res) => {
  try {
    console.log('=== Fetching available employees count (simple) ===');
    
    // Get all active masters
    const masters = await AttendanceMaster.find({ isActive: true }).select('empId').lean();
    const masterEmpIds = masters.map(m => m.empId);

    // Get all employees - filter by businessType (default to restaurant for HRMS)
    const businessTypeFilter = req.query.businessType || "restaurant";
    const employees = await Employee.find({ businessType: businessTypeFilter }).lean();
    const availableEmployees = employees.filter(emp => !masterEmpIds.includes(emp.employeeId));

    console.log(`Total employees: ${employees.length}`);
    console.log(`Masters: ${masters.length}`);
    console.log(`Available: ${availableEmployees.length}`);

    res.status(200).json({
      success: true,
      count: availableEmployees.length,
      totalEmployees: employees.length,
      mastersCount: masters.length,
      data: availableEmployees.slice(0, 5) // Return first 5 for preview
    });
  } catch (error) {
    console.error('Error in getAvailableEmployeesCount:', error);
    // Fallback - return 0
    res.status(200).json({
      success: true,
      count: 0,
      totalEmployees: 0,
      mastersCount: 0,
      fallback: true
    });
  }
};

/**
 * Get available employees for bulk creation (SIMPLE VERSION)
 */
exports.getAvailableEmployeesForMaster = async (req, res) => {
  try {
    console.log('=== Fetching available employees for bulk (simple) ===');
    
    const {
      page = 1,
      limit = 10,
      search = '',
      sortBy = 'name',
      sortOrder = 'ascending'
    } = req.query;

    // Get all active masters
    const masters = await AttendanceMaster.find({ isActive: true }).select('empId').lean();
    const masterEmpIds = masters.map(m => m.empId);

    // Get all employees - filter by businessType (default to restaurant for HRMS)
    const businessTypeFilter = req.query.businessType || "restaurant";
    let employees = await Employee.find({ businessType: businessTypeFilter }).lean();

    // Filter out employees with masters
    let availableEmployees = employees.filter(emp => !masterEmpIds.includes(emp.employeeId));

    // Apply search
    if (search && search.trim()) {
      const searchTerm = search.trim().toLowerCase();
      availableEmployees = availableEmployees.filter(emp => 
        emp.name.toLowerCase().includes(searchTerm) ||
        emp.empId.toLowerCase().includes(searchTerm) ||
        emp.department.toLowerCase().includes(searchTerm) ||
        emp.designation.toLowerCase().includes(searchTerm)
      );
    }

    // Apply sorting
    availableEmployees.sort((a, b) => {
      let aVal = a[sortBy] || '';
      let bVal = b[sortBy] || '';
      
      if (sortBy === 'dateOfJoining') {
        aVal = new Date(a[sortBy] || 0);
        bVal = new Date(b[sortBy] || 0);
      } else {
        aVal = aVal.toString().toLowerCase();
        bVal = bVal.toString().toLowerCase();
      }
      
      if (sortOrder === 'ascending') {
        return aVal > bVal ? 1 : -1;
      } else {
        return aVal < bVal ? 1 : -1;
      }
    });

    // Apply pagination
    const pageNum = parseInt(page);
    const limitNum = parseInt(limit);
    const startIndex = (pageNum - 1) * limitNum;
    const endIndex = startIndex + limitNum;
    const paginatedEmployees = availableEmployees.slice(startIndex, endIndex);

    console.log(`Returning ${paginatedEmployees.length} of ${availableEmployees.length} available employees`);

    res.status(200).json({
      success: true,
      count: paginatedEmployees.length,
      totalCount: availableEmployees.length,
      totalPages: Math.ceil(availableEmployees.length / limitNum),
      currentPage: pageNum,
      data: paginatedEmployees.map(emp => ({
        ...emp,
        // Remove sensitive fields
        bankName: undefined,
        accountNumber: undefined,
        ifscCode: undefined,
        branch: undefined,
        basicSalary: undefined,
        hra: undefined,
        conveyance: undefined,
        medicalAllowance: undefined,
        specialAllowance: undefined,
        pf: undefined,
        professionalTax: undefined,
        tds: undefined,
        otherDeductions: undefined,
        grossSalary: undefined,
        netSalary: undefined
      }))
    });
  } catch (error) {
    console.error('Error in getAvailableEmployeesForMaster:', error);
    res.status(500).json({
      success: false,
      message: 'Error fetching available employees',
      error: error.message
    });
  }
};